logging:
  level:
    org.springframework.security: INFO ERROR DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      registerWithEureka: true
      fetchRegistry: true
      defaultZone: http://localhost:8761/registry-service/eureka

spring:
  rabbitmq:
    host: localhost