logging:
  level:
    org.springframework.security: INFO, ERROR, DEBUG

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  rabbitmq:
    host: localhost